config/routes.rb
Rails.application.routes.draw do
  get 'pages/new'
  get 'projects/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tasks#home'

  get '/new', to:'tasks#new'
  post '/create', to:'tasks#create'
  get '/:id/edit', to: 'tasks#edit'
  patch '/:id/update', to:'tasks#update'
  post '/:id/destroy', to:'tasks#destroy'

  get '/new', to:'projects#new'
  post '/create2', to:'projects#create_project'
  get '/edit_project/:id', to:'projects#edit_project', as: 'edit_project'
  patch '/update_project/:id', to:'projects#update_project', as: 'update_project'
  #post '/destroy_project/:id', to:'projects#destroy_project', as: 'destroy_project'

  get '/by_project', to:'pages#by_project'

  #match '/by_project/:id', to:'pages#by_project'

  resources :tasks
  #resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #def all
    #@project = Project.all
    #@tasks = Task.all.order(limit_date: "ASC")
  #end

  def by_project
    @p_id = params[:id]
    @project = Project.all
    @tasks = Task.where(project_id:@p_id).order(limit_date: "ASC")
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def create_project
    @project = Project.new(project_params)

    if @project.save
      flash[:success] = 'プロジェクトが追加されました'
      #redirect_to @task
      redirect_to controller: 'tasks', action: 'home'
    else
      flash[:danger] = 'プロジェクトが追加されません'
      render :new
    end
  end

  def edit_project
    @project = Project.find(params[:id])
  end

  def update_project
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to controller: 'tasks', action: 'home'
  end

  def destroy_project
    @project = Project.find(params[:id])
    @project.destroy
    flash[:success] = 'プロジェクトが削除されました'
    redirect_to root_path
  end

  def project_params
  params.require(:project).permit(:name)
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def home
    @project = Project.all
    @tasks = Task.all.order(limit_date: "ASC")
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:success] = 'タスクが追加されました'
      #redirect_to @task
      redirect_to controller: 'tasks', action: 'home'
    else
      flash[:danger] = 'タスクが追加されません'
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to controller: 'tasks', action: 'home'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:success] = 'タスクが削除されました'
    redirect_to root_path
  end

  def task_params
  params.require(:task).permit(:content, :limit_date, :project_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "ToDo", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/by_project.html.erb
<body>
<div class="container">
  <!--<div class="l-margin"></div>-->
<div class="contents">
<br><h1><%= "#{Project.find(@p_id).name}" %></h1>
<%= link_to 'プロジェクト名を変更', edit_project_path(Project.find(@p_id))%><br><br>
  <ul style="list-style: none;"
    <% @tasks.each do |task| %>
    <li>
      <%= task.limit_date %> <%= task.content %>
      <%= link_to image_tag("done.png", alt: "Done", :size => "25x25"), task, method: :delete %>
      <%= link_to image_tag("edit.png", alt: "Edit", :size => "25x25"), edit_task_path(task) %>
      <%= link_to image_tag("delete.png", alt: "Destroy", :size => "25x25"), task, method: :delete, data:{ confirm: '本当によろしいですか？'} %>

      <%#= link_to 'Edit', edit_task_path(task)%>
      <%#= link_to 'Destroy', task, method: :delete, data:{ confirm: '本当によろしいですか？'} %>
      <%#= link_to 'Done', task, method: :delete %>
    </li>
      <hr width="100%", align="left">
      <%  end %>
      <li><%= link_to '＋タスクの追加', new_path %></li>
  </ul>
</div>
<div class="sidenavi">
<ul style="list-style: none;">
  <br><br>
  <li><%= link_to '＋タスクの追加', new_path %></li>
  <li><%= link_to '＋プロジェクトの追加', :controller => "projects", :action => "new"%></li>
  <br>
  <li><%= link_to '今日', '#' %></li>
  <li><%= link_to '７日以内', '#' %></li>
  <li><%= link_to '全て', root_path %></li>
  <br>
  <li>プロジェクト</li>
  <% @project.each do |p|%>
  <li>
    <%= link_to "#{p.name}", :controller => "pages", :action => "by_project" , id: p.id %>
</li>
  <% end %>
</ul>
</div>
</div>
</body>

app/views/projects/edit_project.html.erb
<h1>Update Project</h1>

<%= form_for(@project, :url => {controller: 'projects', action: 'update_project'}) do |f| %>
  <%= f.label :name, 'Project' %>
  <%= f.text_field :name %>

  <%= f.submit 'Update Project' %>
<% end %>

<%= link_to 'Task List', root_path %>

app/views/projects/new.html.erb
<h1>Create New Project</h1>

<%= form_for(@project, :url => {controller: 'projects', action: 'create_project'}) do |f| %>
  <%= f.label :name, 'Project' %>
  <%= f.text_field :name %>
  <%= f.submit 'Create Project' %>
<% end %>

<%= link_to 'Task List', root_path %>

app/views/tasks/edit.html.erb
<h1>Update Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :content, 'Task' %>
  <%= f.text_field :content %>
  <%= f.label :limit_date, 'Deadline' %>
  <%= f.text_field :limit_date %>

  <%= f.submit 'Update Task' %>
<% end %>

<%= link_to 'Task List', root_path %>

app/views/tasks/home.html.erb
<body>
<div class="container">
  <!--<div class="l-margin"></div>-->
<div class="contents">
<br><h1>全てのタスク</h1><br>
  <ul style="list-style: none;"
    <% @tasks.each do |task| %>
    <li><%= task.limit_date %> <%= task.content %>
      <%= link_to image_tag("done.png", alt: "Done", :size => "25x25"), task, method: :delete %>
      <%= link_to image_tag("edit.png", alt: "Edit", :size => "25x25"), edit_task_path(task) %>
      <%= link_to image_tag("delete.png", alt: "Destroy", :size => "25x25"), task, method: :delete, data:{ confirm: '本当によろしいですか？'} %>
      <%#= link_to 'Edit', edit_task_path(task)%>
      <%#= link_to 'Destroy', task, method: :delete, data:{ confirm: '本当によろしいですか？'} %>
      <%#= link_to 'Done', task, method: :delete %></li>
      <hr width="100%", align="left">
      <%  end %>
  </ul>
</div>
<div class="sidenavi">
<ul style="list-style: none;">
  <br><br>
  <li><%= link_to '＋タスクの追加', new_path %></li>
  <li><%= link_to '＋プロジェクトの追加', :controller => "projects", :action => "new"%></li>
  <br>
  <li><%= link_to '今日', '#' %></li>
  <li><%= link_to '７日以内', '#' %></li>
  <li><%= link_to '全て', root_path %></li>
  <hr width="90%", align="left">
  <li>プロジェクト</li>
  <% @project.each do |p|%>
  <li>
    <%= link_to "#{p.name}", :controller => "pages", :action => "by_project" , id: p.id %>
</li>
  <% end %>
</ul>
</div>
</div>
</body>

app/views/tasks/new.html.erb
<h1>Create New Task</h1>

<%= form_for(@task, url:create_path) do |f| %>
  <%= f.label :content, 'Task' %>
  <%= f.text_field :content %>
  <%= f.label :limit_date, 'Deadline' %>
  <%= f.text_field :limit_date %>
  <%= f.label :project_id %>
    <%= f.collection_select :project_id, Project.all, :id, :name %>

  <%= f.submit 'Create Task' %>
<% end %>

<%= link_to 'Task List', root_path %>